<a href="https://colab.research.google.com/github/Ravindrakumarnayak/Machine_learning/blob/main/bagging_stacking_boosting_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from pandas import read_csv

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import  BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [3]:
filename="/content/pima-indians-diabetes.csv"
names=["preg","plas","pres","skin","test","mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values
x =array[:,0:8]
y=array[:,8]
seed=7
kfold=KFold(n_splits=10, random_state=seed,shuffle=True) # evaluation method
cart= DecisionTreeClassifier()
num_trees=100

model=BaggingClassifier(estimator= cart,n_estimators=num_trees,random_state=None) # classifier
result=cross_val_score(model,x,y,cv=kfold)

In [4]:
result

array([0.76623377, 0.79220779, 0.72727273, 0.79220779, 0.80519481,
       0.83116883, 0.71428571, 0.77922078, 0.78947368, 0.75      ])

In [5]:
result.mean()

0.7747265892002735

In [6]:
# random forest

from pandas import read_csv

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [7]:
from scipy.sparse import random
filename="/content/pima-indians-diabetes.csv"
names=["preg","plas","pres","skin","test","mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values
x =array[:,0:8]
y=array[:,8]
seed=7
max_features=3

kfold=KFold(n_splits=10)# bootstrap
cart= DecisionTreeClassifier()
num_trees=100

model=RandomForestClassifier(n_estimators=num_trees  , max_features=max_features) # classifier
result=cross_val_score(model,x,y,cv=kfold)

In [8]:
result

array([0.7012987 , 0.80519481, 0.72727273, 0.64935065, 0.76623377,
       0.80519481, 0.85714286, 0.85714286, 0.68421053, 0.76315789])

In [9]:
result.mean()

0.7616199589883801

In [10]:
# ada boost


In [11]:
from sklearn.ensemble import  AdaBoostClassifier

In [13]:
filename="/content/pima-indians-diabetes.csv"
names=["preg","plas","pres","skin","test","mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values
x =array[:,0:8]
y=array[:,8]
seed=7
max_features=3



num_trees=10

kfold=KFold(n_splits=10,random_state=seed, shuffle=True )# bootstrap
model=AdaBoostClassifier(n_estimators=num_trees  ,random_state=seed) # classifier
result=cross_val_score(model,x,y,cv=kfold)

In [14]:
result

array([0.80519481, 0.74025974, 0.67532468, 0.81818182, 0.80519481,
       0.79220779, 0.71428571, 0.75324675, 0.78947368, 0.77631579])

In [16]:
result.mean()

0.7669685577580314

In [ ]:
# stacking

In [32]:
from pandas import read_csv

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [33]:
estimators=[]


model1=LogisticRegression(max_iter=100)
estimators.append(("logistic",model1))

model2=DecisionTreeClassifier()
estimators.append(("cart",model2))


model3=SVC()
estimators.append(("svc",model3))


#essemble model
essemble=VotingClassifier(estimators)
result=cross_val_score(model,x,y,cv=kfold)



In [34]:
result

array([0.80519481, 0.74025974, 0.67532468, 0.81818182, 0.80519481,
       0.79220779, 0.71428571, 0.75324675, 0.78947368, 0.77631579])

In [35]:
result.mean()

0.7669685577580314