<a href="https://colab.research.google.com/github/Ravindrakumarnayak/Machine_learning/blob/main/feature_engineering_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from pandas import read_csv
from numpy import printoptions # for decimal value selection
from sklearn.feature_selection import SelectKBest # for univariate selection
from sklearn.feature_selection import chi2

In [6]:
filename="/content/pima-indians-diabetes.data4.csv"
names=["preg","plas","pres","skin",'test',"mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values
dataframe.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [8]:
dataframe.shape

(768, 9)

In [7]:
x=array[:,0:8]
y=array[:,8]

In [ ]:
# feature extraction

In [17]:
from numpy.core.arrayprint import set_printoptions
test=  SelectKBest(score_func=chi2, k=5)
fit=test.fit(x,y)
scores=set_printoptions(precision=4)
print(fit.scores_)

[ 111.5197 1411.887    17.6054   53.108  2175.5653  127.6693    5.3927
  181.3037]


In [12]:
features=fit.transform(x)
features.shape

(768, 5)

In [18]:
x=pd.DataFrame(fit.scores_).T # T for  transform list to dataframe

In [19]:
x

0            1          2  ...           5         6           7
0  111.519691  1411.887041  17.605373  ...  127.669343  5.392682  181.303689

[1 rows x 8 columns]

In [22]:
x.columns=names[:8]
x

preg         plas       pres  ...        mass      pedi         age
0  111.519691  1411.887041  17.605373  ...  127.669343  5.392682  181.303689

[1 rows x 8 columns]

In [23]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [24]:
sorted_x=x.sort_values(by=0, ascending=False, axis=1)

In [26]:
sorted_x # high chi2 value will be placed high to low... by is used for index of rows, we have taken 0th row(test,plas,age,mass and preg is 5 best feature,we got)

test         plas         age  ...      skin       pres      pedi
0  2175.565273  1411.887041  181.303689  ...  53.10804  17.605373  5.392682

[1 rows x 8 columns]

In [30]:
# feature RFE

from pandas import read_csv
from sklearn.feature_selection import RFE # recursive feature engineering
from sklearn.linear_model import LogisticRegression

In [29]:
filename="/content/pima-indians-diabetes.data4.csv"
names=["preg","plas","pres","skin",'test',"mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values

x=array[:,0:8]
y=array[:,8]

In [33]:
#feature extraction
model=LogisticRegression(max_iter=400) # model is object we create
rfe=RFE(model) # we have passed model to RFE model
fit=rfe.fit(x,y) # fit method is used in rfe and passed input x and y

In [34]:

fit.n_features_

4

In [35]:
fit.support_ # important feature is True

array([ True,  True, False, False, False,  True,  True, False])

In [36]:
# now mapping column names

In [37]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [39]:
fit.ranking_ # ranking method is used for selcting features based on rank shown

array([1, 1, 3, 5, 4, 1, 1, 2])

In [40]:
# decision tree classifier

In [48]:
from sklearn.tree import DecisionTreeClassifier

filename="/content/pima-indians-diabetes.data4.csv"
names=["preg","plas","pres","skin",'test',"mass","pedi","age","class"]
dataframe=read_csv(filename,names=names)
array=dataframe.values

x=array[:,0:8]
y=array[:,8]


model=DecisionTreeClassifier()
model.fit(x,y)
print(model.feature_importances_)

[0.0596 0.3195 0.0878 0.0208 0.0285 0.2348 0.1288 0.1202]


In [49]:
sorted_list=model.feature_importances_
print("feature importance=",model.feature_importances_)
sorted_list.sort()
print("sorted feature_importances_=",sorted_list)

feature importance= [0.0596 0.3195 0.0878 0.0208 0.0285 0.2348 0.1288 0.1202]
sorted feature_importances_= [0.0208 0.0285 0.0596 0.0878 0.1202 0.1288 0.2348 0.3195]


In [50]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']